name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build app
        uses: gradle/gradle-command-action@v1
        with:
          arguments: copyExtensionArtifacts bundlePlaystoreRelease
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      # Sign app bundle and create release for tags

      - name: Sign app bundle
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LiveTL/android'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/playstoreRelease
          signingKeyBase64: ${{ secrets.KEY_B64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}

      - name: Prepare build metadata
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LiveTL/android'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

          if [[ "${{ github.event.ref }}" =~ "-beta" ]]
          then
            echo "GOOGLE_PLAY_TRACK=beta" >> $GITHUB_ENV
          else
            echo "GOOGLE_PLAY_TRACK=production" >> $GITHUB_ENV
          fi

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LiveTL/android'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: LiveTL for Android ${{ env.VERSION_TAG }}
          files: |
            ${{ env.SIGNED_RELEASE_FILE }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Google Play
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LiveTL/android'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.livetl.android
          releaseFile: ${{ env.SIGNED_RELEASE_FILE }}
          mappingFile: app/build/outputs/mapping/playstoreRelease/mapping.txt
          track: ${{ env.GOOGLE_PLAY_TRACK }}
          whatsNewDirectory: distribution/whatsnew
